# action.yml
name: 'Zulip Archive'
description: 'Publish Zulip archive in GitHub pages'
inputs:
  site:
    description: 'URL of Zulip organization'
    required: true
  key:
    description: 'API key of the bot'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.site }}
    - ${{ inputs.key }}
